version: '3.8'
services:
  api:
    depends_on:
      - postgres
    environment:
      NODE_ENV: ${NODE_ENV}
    build:
      context: .
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    restart: unless-stopped
    command: npm run start:${NODE_ENV}
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - '5432:5432'
    volumes:
      - gymnasts-postgres:/var/lib/postgresql/data

volumes:
  gymnasts-postgres:
    driver: local
