version: '3.8'
services:
  api:
    environment:
      - NODE_ENV:${NODE_ENV}
      - AWS_ACCESS_KEY_ID:${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY:${AWS_SECRET_ACCESS_KEY}
    build:
      context: .
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - 9229:9229
    volumes:
      - ./app:/usr/src/app
      - ./usr/src/app/node_modules
    restart: unless-stopped
    command: npm run start:${NODE_ENV}