version: '3.8'
services:
  api:
    depends_on:
      - postgres
    build:
      context: .
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    command: npm run start:${NODE_ENV}
    container_name: gymnastics-api
  
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - gymnasts:/var/lib/postgresql/data
    container_name: postgres-db
    ports:
    - 5432:5432

volumes:
  gymnasts:
    driver: local
